server:
  port: 8181
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/clay_store
    username: postgres
    password: n0p0d
    driver-class-name: org.postgresql.Driver 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  